export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const CLEAR = 'CLEAR';

export const FETCHING_DATA_REQUEST = 'FETCHING_DATA_REQUEST';

export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';

export const ORDERCART_REQUEST = 'ORDERCART_REQUEST';
export const ORDERCART_UPDATE = 'ORDERCART_UPDATE';